### ISSUE TITLE
DeveloperGuide - General Improvements

### ISSUE THREAD

**Issue by ryanchua00** [AY2223S2-CS2103T-T17-4/tp#107]
Comments received:
1. There are some change to the UML diagrams of high-level components but it lacks corresponding description to each new small class the team implement inside high-level components(e.g FishListPanel, TaskListPanel in UI component) 
2. What does the alternative design in the Automatic Feeding Reminders mean? It seems unclear to me. 
3. The step 1, 2, ... in implementation could stand out more (e.g. use bullet point form). 
4. This seems to have different style from the rest of the DG “As a FishTracker application, we provide a way for fishkeepers to track the LastFedDates of all their fishes, as having multiple tanks and fishes makes feeding difficult to keep track of without a tracking system”.

**Comment by bokuanT** [comment]
we done wit this
