### ISSUE TITLE
[PE-D][Tester C] `fish sort by/n` after `fish view 6` does not show all fishes as shown and does not display an error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-4/tp#184]
![Screenshot 2023-03-31 at 3.00.53 PM.png](https://raw.githubusercontent.com/cjyothika/ped/main/files/f839cfd3-288f-401f-9946-f1b51e444113.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: cjyothika/ped#10

**Comment by ryanchua00** [comment]
This is a feature, only sorts fish that are present.
I'll add a tip in the UG
