### ISSUE TITLE
[PE-D][Tester C] `fish sort by/s` does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-4/tp#189]
![Screenshot 2023-03-31 at 3.13.15 PM.png](https://raw.githubusercontent.com/cjyothika/ped/main/files/6f533e33-d872-4ed0-8563-92c7aa892fa2.png)

tempSpeciesA Dory is below tempSpeciesB Marlin after `fish sort by/s` as shown above.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: cjyothika/ped#11

**Comment by ryanchua00** [comment]
This is not an functionality bug. Tester has mixed up name and species of fishes. 
Perhaps species is now not as prominent, but Dory's species is `Tetra`, whilst Marlin's species is `Parrot Fish`. Correctly, Dory is sorted after Marlin.
