### ISSUE TITLE
[PE-D][Tester A] addReadings documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-4/tp#197]
It is also unclear how each reading type should be added. UG suggests a number can be entered for the reading but does not share where this number can be inputted. 
For example the format given `tank addReadings TANK_INDEX` does not say anything about inputting reading values.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Bransonlj/ped#4

**Comment by bokuanT** [comment]
https://github.com/bokuanT/tp/blob/branch-UserGuide/docs/UserGuide.md#adding-a-set-of-readings-tank-addreadings
